paginate: 5
paginate_path: "/page/:num/"
permalink: /:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md", "Gemfile", "Gemfile.lock", "LICENSE", "assets/images.psd", "run.ps1", "git-clone.ps1", "wordpress.xml", "CNAME", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md"]

title : Programcıdan Programcıya
tagline: Bir programcının dünyası...
author :
  name : Engin Polat
  email : engin@enginpolat.com
  github : polatengin
  twitter : polatengin
  feedburner : polatengin

production_url : http://polatengin.github.io

url: https://enginpolat.com

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false

plugins: ["jekyll-sitemap", "jekyll-paginate"]
