CREATE TABLE BACKUP_TEST (F1 VARCHAR(37),F2 VARCHAR(37),F3 VARCHAR(37),F4 VARCHAR(37),F5 VARCHAR(37),F6 VARCHAR(37),F7 VARCHAR(37),F8 VARCHAR(37),F9 VARCHAR(37),F10 VARCHAR(37))

GO

DECLARE @ILOOP INT = 6000000
WHILE (@ILOOP > 0)
BEGIN
	INSERT INTO BACKUP_TEST
	SELECT
		NEWID(),
		NEWID(),
		NEWID(),
		NEWID(),
		NEWID(),
		NEWID(),
		NEWID(),
		NEWID(),
		NEWID(),
		NEWID()

	SET @ILOOP -= 1
END

GO

INSERT INTO BACKUP_TEST
SELECT * FROM BACKUP_TEST WITH (NOLOCK)

GO

BACKUP DATABASE
  AdventureWorks2008R2
TO DISK = 'C:\EnginPOLAT\AdventureWorks2008R2_Backup.bak'
WITH
  NOFORMAT,
  INIT,
  SKIP,
  NOREWIND,
  NOUNLOAD,
  STATS = 10

GO

BACKUP DATABASE
  AdventureWorks2008R2
TO DISK = 'C:\EnginPOLAT\AdventureWorks2008R2_Backup_Compressed.bak'
WITH
  COMPRESSION,
  NOFORMAT,
  INIT,
  SKIP,
  NOREWIND,
  NOUNLOAD,
  STATS = 10